### ISSUE TITLE
Odometry: timestamp

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#109]
![image](https://user-images.githubusercontent.com/8008227/84565644-c1ee9b00-ad6a-11ea-98ce-e2506e692fdb.png)

**Comment by davidoort** [comment]
This is because  odom messages currently do not get a message timestamp and the delay is calculated between timestamp in the header and the current timestamp. So with no timestamp set, the delay is equal to the current timestamp. Thus the large numbers.
