### ISSUE TITLE
Simulator packaged version somethings everything is bright and white

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#115]
![crash image](https://user-images.githubusercontent.com/8008227/84875140-da6df680-b085-11ea-95dd-6ec249d61c91.PNG)

When restarting the simulator somehow i got this output. Driving around works fine but everything just looks like this.

**Comment by SijmenHuizenga** [comment]
After a restart i got the VK_ERROR_DEVICE_LOST error, suggesting that something was wrong with my videocard. The previous shutdown of the simulator was probably unclean. 

After closing some other programs (slack, discord, steam, chrome) and waiting for a few minutes, the problem was gone and everything worked fine again.

**Comment by SijmenHuizenga** [comment]
It keeps happening. Every few times it goes white and then after a restart I get VK_ERROR_DEVICE_LOST. This is really annoying.

**Comment by SijmenHuizenga** [comment]
It might be good to note that this is in the packaged windows 64x version

**Comment by davidoort** [comment]
I've never observed this on the Ubuntu instances either

**Comment by SijmenHuizenga** [comment]
On google cloud, using the beta-3 binaries sometimes the white thing as well. Less often than on my computer and never with the `VK_ERROR_DEVICE_LOST` error.

**Comment by SijmenHuizenga** [comment]
When selecting `Package Project -> Build Configuration -> DebugGame` this problem doesn't happen.

**Comment by SijmenHuizenga** [comment]
Added beta-3-debug.zip to the beta-3 release. Use that one to not have this problem.

**Comment by SijmenHuizenga** [comment]
From beta-4 onward we will just be doing debug releases to not have this problem.
