### ISSUE TITLE
Unreal Training Map contains 19296 cones

### ISSUE THREAD

**Issue by davidoort** [FS-Online/Formula-Student-Driverless-Simulator#140]
So far I have just tried the Training Map, but there the following print statement in `airsim_ros_wrapper.cpp` shows a value of **19296** which is obviously incorrect.
![image (17)](https://user-images.githubusercontent.com/21220927/87248765-b4a4f900-c45b-11ea-90f6-f533ca5abdb4.png)

**Comment by SijmenHuizenga** [comment]
![image](https://user-images.githubusercontent.com/8008227/87249742-3cd9cd00-c461-11ea-9515-44f8bdba5d36.png)

**Comment by davidoort** [comment]
It is a map problem. Training map contains 19296 cones but other maps such as IM_MAP1 contains 480 cones. Renaming the issue now

**Comment by davidoort** [comment]
This is issue is only a problem when running a semi-autonomous system that makes use of the `fsds/testing_only/track` topic.

**Comment by smnschfr** [comment]
We've seen the same issue and were able to filter out the surplus cones by checking for location duplicates. After doing that, the map is correct.

**Comment by SijmenHuizenga** [comment]
Cool! I will fix the training map monday.

**Comment by SijmenHuizenga** [comment]
Progress? 
![image](https://user-images.githubusercontent.com/8008227/87288382-8f67c780-c4fb-11ea-9907-c339e0cd68e5.png)

**Comment by SijmenHuizenga** [comment]
> The Construction Script is designed to execute upon creation of the Blueprint object, and **again whenever that object is updated in some way.** ([source](https://docs.unrealengine.com/en-US/Resources/ContentExamples/Blueprints/1_4/index.html))

In the spline_cones we were using the construction script to create the cones and added them to an array. When the object was updated all cones were created again. After adding a clear of the arrays each update it works

![image](https://user-images.githubusercontent.com/8008227/87291316-6cd7ad80-c4ff-11ea-8119-836f9b77c8a7.png)


![image](https://user-images.githubusercontent.com/8008227/87291283-621d1880-c4ff-11ea-9749-ab7041ccaa1e.png)
