### ISSUE TITLE
Track shows black, flickering areas

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#17]
![Screenshot from 2020-05-08 22-54-58](https://user-images.githubusercontent.com/8008227/81448665-0e98f200-917f-11ea-87eb-88f8e8ade549.png)

Those black spot's shouldn't be there.

**Comment by davidoort** [comment]
Maybe related to this but sometimes I have tried to drive the car on these roads and it seemed to collide against invisible objects

**Comment by SijmenHuizenga** [comment]
At this moment we are not racing on these tracks so this has a low priority.

**Comment by SijmenHuizenga** [comment]
We have moved away from these maps because they impact performance too much. So we won't be fixing this problem.
