### ISSUE TITLE
Preloading of maps and disciplines in the FSOnline event

### ISSUE THREAD

**Issue by smnschfr** [FS-Online/Formula-Student-Driverless-Simulator#185]
In the [docs](https://github.com/FS-Online/Formula-Student-Driverless-Simulator/blob/master/docs/integration-handbook.md), the "Starting" section explains how the AS has to deal with different tracks and disciplines. 
Does this part need to be automated, or can we simply wait for the information to be communicated by race control ("up next: track B autocross") , login via SSH and run the appropriate launchfiles?

**Comment by SijmenHuizenga** [comment]
On every competition day, the team's remote access to the instances is blocked and restored after the events are finished. During the day, between the events, you won't be able to access your autonomous system So yes, your autonomous system must be able to automatically switch between autocross and trackdrive.

**Comment by SijmenHuizenga** [comment]
If you have any more questions, feel free to re-open :+1:

**Comment by smnschfr** [comment]
After sending /fsds/signal/finished, can we assume that /fsds/signal/go will be stopped soon*? 

*like within 60 seconds
