### ISSUE TITLE
Problem with launching 1.1.0 released version

### ISSUE THREAD

**Issue by KarasevPavel** [FS-Online/Formula-Student-Driverless-Simulator#196]
Hello! I has tried to run an FSDS.exe as was mentioned in Getting Started instruction https://fs-online.github.io/Formula-Student-Driverless-Simulator/latest/getting-started/, but I had only a black screen with a title in the left upper corner of the screen, as on the screenshot. I am using Windows 10 Pro with Formula-Student-Driverless-Simulator repository installed in my Windows home directory.

![screenshot](https://user-images.githubusercontent.com/48162222/88798552-bab20e00-d1ad-11ea-9c64-7856d8785bd7.PNG)

**Comment by KarasevPavel** [comment]
Solved! I have installed a GeForce Game Ready Driver for my GTX1650 GPU of version 451.67 (latest version) and problem was solved.

**Comment by SijmenHuizenga** [comment]
Welcome to the project 👋 

Glad you solved it!
