### ISSUE TITLE
Camera step size bug

### ISSUE THREAD

**Issue by zalandemeter12** [FS-Online/Formula-Student-Driverless-Simulator#204]
In the fsds_ros_bridge_camera.cpp file on line 71 the num_bytes parameter is wrong and set to 8. I solved my issue by setting it to 3.
![error log](https://user-images.githubusercontent.com/33003291/89110388-6081a900-d44a-11ea-84d9-f189bcda9342.png)

**Comment by SijmenHuizenga** [comment]
Thanks for reporting! I will look into it sunday so that a fixed version is available monday before competition testday 1.
