### ISSUE TITLE
Validate that the dimensions of the cone are in line with rules

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#40]
The rules describe a specific type and size of cone. We have to make sure simulated cones are the right size and colors.

Cone requirements as descibed in the fsg competition handbook 2020 v1.0
![image](https://user-images.githubusercontent.com/8008227/85952677-36305d80-b96b-11ea-871b-61e931401f6a.png)

**Comment by SijmenHuizenga** [comment]
Measurements in unreal engine. All units are cm.

**Small cones in the world**

Side view:
![image](https://user-images.githubusercontent.com/8008227/85952616-d9cd3e00-b96a-11ea-91fc-0625ba82eea6.png)

Top view:
![image](https://user-images.githubusercontent.com/8008227/85952652-113bea80-b96b-11ea-9f9f-2cdd9c7b78a3.png)

**Large cones in the world**

Side view:
![image](https://user-images.githubusercontent.com/8008227/85952708-81e30700-b96b-11ea-8e09-45e3c1f14364.png)


Top view:
![image](https://user-images.githubusercontent.com/8008227/85952693-5eb85780-b96b-11ea-828c-0a5239f2eab2.png)

**Comment by SijmenHuizenga** [comment]
Since nobody objected above sizes, I think it is safe to assume cone dimensions are close enough to the real cones to be used in competition. Closing this ticket.

**Comment by davidoort** [comment]
Are these sizes and pictures somewhere in the docs? It might be useful for people developing vision algorithms

**Comment by SijmenHuizenga** [comment]
No, they are not in the docs. These are the same sizes of cones used in all driverless formula student competitions, so I assume people know them. Could still be nice to mention it though... Maybe we should make a page with cone sizes and track details like distance between blue and yellow cones, maximum curvature, etc

**Comment by Joroba3** [comment]
Perhaps it's been a while, but I just meassured our cones and there's actually quite a bit of variability in (even new) cones. Some where even 30cm tall instead of 32cm.
