### ISSUE TITLE
Car looks customization

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#47]
Figure out how to change the car 3d model and skin without reloading the simulation.

**Comment by davidoort** [comment]
By reloading do you mean restarting or rebuilding the Unreal Project?

**Comment by SijmenHuizenga** [comment]
> By reloading do you mean restarting or rebuilding the Unreal Project?

to be defined ;)

**Comment by SijmenHuizenga** [comment]
so yes, restarting unreal engine :D

**Comment by SijmenHuizenga** [comment]
This has been merged in #126
