### ISSUE TITLE
Notify users of invalid sensor configuration.

### ISSUE THREAD

**Issue by davidoort** [FS-Online/Formula-Student-Driverless-Simulator#79]
Print warnings to console (or send them as logs to the webGUI) if the sensor suite requirements are not compliant with the rules set out in the integration handbook. It is basically a unit test of the teams settings.json file. We might not even have to do it at runtime.

**Comment by smnschfr** [comment]
This would be helpful to get the exact vehicle specifications, too. Right now, I'm not sure about the final data that I can use to calculate whether my sensor placement is compliant to the official rules.

**Comment by SijmenHuizenga** [comment]
@smnschfr I see your problem. Feel free to contact FSOnline if you have questions about the procedures of the competition. Here we can only answer tech-related questions. If you have a sensor configuration that you would like to be validated, feel free to open a ticket here on GitHub or send it to hello@formulastudentonline.com

**Comment by SijmenHuizenga** [comment]
Closing this since FSOnline has passed.
