### ISSUE TITLE
Provide rosbags with example data

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#80]
Record all topics published by the default settings.json into a rosbag while driving with a joystick. The goal is to kickstart teams' development.

**Comment by SijmenHuizenga** [comment]
Problem with this is that there are infinite different sensor suite possibilities. So even if we provide a rosbag, few teams will actually be able to use this.

For now I'm closing this issue. If someone wants rosbags, feel free to comment and this can be reopened.

**Comment by davidoort** [comment]
I agree. In addition to the above, please provide a list of topics and a settings.json file so that we can easily record the rosbag for you.
