### ISSUE TITLE
Competition mode ros bridge

### ISSUE THREAD

**Issue by SijmenHuizenga** [FS-Online/Formula-Student-Driverless-Simulator#97]
In competition mode some ros topics shouldn't be published:
* cone positions
* car location odometer

**Comment by davidoort** [comment]
we will mark these topics as temporary to warn teams

**Comment by davidoort** [comment]
We have been discussing the option of allowing teams to use one or both of these topics at the cost of a time penalty which would at least allow them to compete without a finished autonomous system. Hold off fixing this issue until we have a definite plan for this!
